name: CI/CD Pipeline for DigitalCard

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.3.0'

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Deploy to Server
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 3.110.67.210
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/digitalcard
            git pull origin main
            npm install
            pm2 restart digitalcard --update-env
